---
- name: Deploy Apache Webserver with Custom Message
  hosts: Ubuntu
  become: true
  remote_user: ubuntu
  vars:
    welcome_message: "Welcome to our firts web server launch trhougt ansible with dynamic inventory by Patrick Tchamagnie"
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Create custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1 style='color:blue;'>{{ welcome_message }}</h1></body></html>"



- name: Install Git on Ubuntu Clients
  hosts: Ubuntu
  become: true
  remote_user: ubuntu
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
    - name: Verify Git installation
      ansible.builtin.command: git --version
      register: git_version_output

    - name: Display Git version
      ansible.builtin.debug:

- name: Ping Ubuntu Clients
  hosts: Ubuntu  # Ensuring consistency in tag name
  remote_user: ubuntu
  tasks:
    - name: Ping clients
      ansible.builtin.ping:

- name: Ping Amazon Linux Clients
  hosts: AMZ_Linux
  remote_user: ec2-user
  tasks:
    - name: Ping clients
      ansible.builtin.ping:

- name: Debug Ubuntu Clients
  hosts: Ubuntu
  remote_user: ubuntu
  tasks:
    - name: Show name using debug
      ansible.builtin.debug:
        msg: "My name is PATRICK TCHAMAGNIE (Ubuntu Client)"

- name: Debug Amazon Linux Clients
  hosts: AMZ_Linux
  remote_user: ec2-user
  tasks:
    - name: Show name using debug
      ansible.builtin.debug:
        msg: "My name is PATRICK TCHAMAGNIE (Amazon Linux Client)"